#!/usr/bin/env node
/**
 * Scan wiki/ and emit docsify sidebar with folder hierarchy.
 * Does NOT touch entry bodies or run generate_wiki.py.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const WIKI = path.join(ROOT, 'wiki');
const OUT = path.join(WIKI, '_Sidebar.generated.md');

const SKIP_DIRS = new Set(['_templates']);
const SKIP_FILES = new Set([
  '_Footer.md',
  '_Sidebar.md',
  '_Sidebar.generated.md',
  '_generated-stats.md',
]);

const FOLDER_LABELS = {
  banks: '银行',
  cards: '信用卡',
  categories: '分类',
  glossary: '术语',
  meta: '元文档',
  pages: '页面',
  posts: '文章',
  products: '产品',
  'reward-programs': '积分体系',
  sources: '来源',
};

function parseFrontmatter(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) {
    return { title: null, content };
  }
  const titleMatch = match[1].match(/^title:\s*(['"]?)(.+?)\1\s*$/m);
  return { title: titleMatch ? titleMatch[2] : null, content };
}

function pageLabel(filePath, fallback) {
  try {
    const { title } = parseFrontmatter(filePath);
    return title || fallback;
  } catch {
    return fallback;
  }
}

function toDocsifyPath(relativePath) {
  return '/wiki/' + relativePath.split(path.sep).join('/');
}

function folderHeaderLine(dir, prefix, folderName) {
  const rel = prefix + '_index.md';
  const indexPath = path.join(dir, '_index.md');
  const label = FOLDER_LABELS[folderName] || pageLabel(indexPath, folderName);
  return '- [' + label + '](' + toDocsifyPath(rel) + ')';
}

function ensureTopLevelIndex(folderName) {
  const dir = path.join(WIKI, folderName);
  const indexPath = path.join(dir, '_index.md');
  if (fs.existsSync(indexPath)) {
    return;
  }
  const label = FOLDER_LABELS[folderName] || folderName;
  const content = '---\ntitle: \'' + label + '\'\n---\n\n# ' + label + '\n';
  fs.writeFileSync(indexPath, content, 'utf8');
  console.log('Created ' + path.relative(ROOT, indexPath));
}

function listMarkdownFiles(dir, prefix = '') {
  const entries = fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name, 'zh-Hans')
  );

  const lines = [];

  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name) || entry.name.startsWith('.')) {
        continue;
      }
      const subDir = path.join(dir, entry.name);
      const subPrefix = prefix + entry.name + path.sep;
      lines.push(folderHeaderLine(subDir, subPrefix, entry.name));
      for (const subLine of listMarkdownFiles(subDir, subPrefix)) {
        lines.push('  ' + subLine);
      }
      continue;
    }

    if (!entry.isFile() || !entry.name.endsWith('.md')) {
      continue;
    }
    if (entry.name === '_index.md' || SKIP_FILES.has(entry.name)) {
      continue;
    }

    const rel = prefix + entry.name;
    const fallback = entry.name.replace(/\.md$/, '');
    const label = pageLabel(path.join(dir, entry.name), fallback);
    lines.push('- [' + label + '](' + toDocsifyPath(rel) + ')');
  }

  return lines;
}

function buildSidebar() {
  const homeLabel = pageLabel(path.join(WIKI, 'Home.md'), '首页');
  const lines = [
    '<!-- Auto-generated by scripts/build-nav.mjs; do not edit -->',
    '',
    '- [' + homeLabel + '](/wiki/Home.md)',
    '',
  ];

  const topEntries = fs.readdirSync(WIKI, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name, 'zh-Hans')
  );

  for (const entry of topEntries) {
    if (!entry.isDirectory()) {
      continue;
    }
    if (SKIP_DIRS.has(entry.name) || entry.name.startsWith('.')) {
      continue;
    }

    ensureTopLevelIndex(entry.name);
    lines.push(folderHeaderLine(path.join(WIKI, entry.name), entry.name + path.sep, entry.name));
    for (const subLine of listMarkdownFiles(path.join(WIKI, entry.name), entry.name + path.sep)) {
      lines.push('  ' + subLine);
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd() + '\n';
}

const sidebar = buildSidebar();
fs.writeFileSync(OUT, sidebar, 'utf8');
console.log('Wrote ' + path.relative(ROOT, OUT));
