#!/usr/bin/env node
/**
 * Scan wiki/ and emit docsify sidebar with folder hierarchy.
 * Does NOT touch entry bodies or run generate_wiki.py.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const WIKI = path.join(ROOT, 'wiki');
const OUT = path.join(WIKI, '_Sidebar.generated.md');

const SKIP_DIRS = new Set(['_templates']);
const SKIP_FILES = new Set([
  '_Footer.md',
  '_Sidebar.md',
  '_Sidebar.generated.md',
  '_generated-stats.md',
]);

const FOLDER_LABELS = {
  banks: '银行 banks',
  cards: '信用卡 cards',
  categories: '分类 categories',
  glossary: '术语 glossary',
  meta: '元文档 meta',
  pages: '页面 pages',
  posts: '文章 posts',
  'reward-programs': '积分体系 reward-programs',
  sources: '来源 sources',
};

function parseFrontmatter(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) {
    return { title: null, content };
  }
  const titleMatch = match[1].match(/^title:\s*(['"]?)(.+?)\1\s*$/m);
  return { title: titleMatch ? titleMatch[2] : null, content };
}

function pageLabel(filePath, fallback) {
  try {
    const { title } = parseFrontmatter(filePath);
    return title || fallback;
  } catch {
    return fallback;
  }
}

function toDocsifyPath(relativePath) {
  return '/wiki/' + relativePath.split(path.sep).join('/');
}

function listMarkdownFiles(dir, prefix = '') {
  const entries = fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name, 'zh-Hans')
  );

  const lines = [];

  const indexEntry = entries.find((e) => e.isFile() && e.name === '_index.md');
  if (indexEntry) {
    const rel = prefix + '_index.md';
    const label = pageLabel(path.join(dir, '_index.md'), '索引');
    lines.push('- [' + label + '](' + toDocsifyPath(rel) + ')');
  }

  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name) || entry.name.startsWith('.')) {
        continue;
      }
      const subDir = path.join(dir, entry.name);
      const subPrefix = prefix + entry.name + path.sep;
      const folderLabel = FOLDER_LABELS[entry.name] || entry.name;
      lines.push('- ' + folderLabel);
      for (const subLine of listMarkdownFiles(subDir, subPrefix)) {
        lines.push('  ' + subLine);
      }
      continue;
    }

    if (!entry.isFile() || !entry.name.endsWith('.md')) {
      continue;
    }
    if (entry.name === '_index.md' || SKIP_FILES.has(entry.name)) {
      continue;
    }

    const rel = prefix + entry.name;
    const fallback = entry.name.replace(/\.md$/, '');
    const label = pageLabel(path.join(dir, entry.name), fallback);
    lines.push('- [' + label + '](' + toDocsifyPath(rel) + ')');
  }

  return lines;
}

function buildSidebar() {
  const homeLabel = pageLabel(path.join(WIKI, 'Home.md'), '首页');
  const lines = [
    '<!-- Auto-generated by scripts/build-nav.mjs; do not edit -->',
    '',
    '- [' + homeLabel + '](/wiki/Home.md)',
    '',
  ];

  const topEntries = fs.readdirSync(WIKI, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name, 'zh-Hans')
  );

  for (const entry of topEntries) {
    if (!entry.isDirectory()) {
      continue;
    }
    if (SKIP_DIRS.has(entry.name) || entry.name.startsWith('.')) {
      continue;
    }

    const folderLabel = FOLDER_LABELS[entry.name] || entry.name;
    lines.push('- ' + folderLabel);
    for (const subLine of listMarkdownFiles(path.join(WIKI, entry.name), entry.name + path.sep)) {
      lines.push('  ' + subLine);
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd() + '\n';
}

const sidebar = buildSidebar();
fs.writeFileSync(OUT, sidebar, 'utf8');
console.log('Wrote ' + path.relative(ROOT, OUT));
